// Mock data for PostOpGuard prototype
window.VF_DATA = {
  patients: [
    {
      id: "p-paul",
      name: "Paul Hendricks",
      mrn: "MRN-48201",
      age: 67,
      sex: "M",
      procedure: "Left total hip replacement",
      surgeon: "Dr. M. Smith",
      pod: 4, // post-op day
      protocol: "Hip Replacement Protocol v3.2",
      status: "critical",
      trend: "up",
      lastCheckin: "2 min ago",
      lastCheckinAt: "08:42",
      score: 0.86,
      triggers: ["Calf warmth + tenderness (L)", "Missed anticoagulant dose"],
      vitals: {
        hr: { value: 102, unit: "bpm", range: [60, 100], state: "warning" },
        spo2: { value: 95, unit: "%",  range: [94, 100], state: "stable" },
        temp: { value: 99.8, unit: "°F", range: [97, 99.5], state: "warning" },
        pain: { value: 6, unit: "/10", range: [0, 3], state: "warning" },
        bp: { value: "138/86", unit: "mmHg", range: null, state: "warning" }
      },
      meds: [
        { name: "Apixaban 2.5mg",   schedule: "BID",  takenToday: 1, expected: 2, status: "missed-am" },
        { name: "Acetaminophen 500mg", schedule: "Q6H", takenToday: 3, expected: 3, status: "ok" },
        { name: "Oxycodone 5mg",    schedule: "PRN",  takenToday: 2, expected: null, status: "ok" }
      ],
      transcript: [
        { who: "system", t: "08:42:01", text: "Good morning Paul. How are you feeling today, post-op day 4?" },
        { who: "patient", t: "08:42:08", text: "Um… I'm okay, but my left calf is really warm and tender. I haven't taken my blood thinners yet today." },
        { who: "system", t: "08:42:24", text: "I've noted the calf warmth. That's important. Can you tell me — on a scale of 1 to 10, how would you rate the pain in your calf?" },
        { who: "patient", t: "08:42:34", text: "Probably a six. It hurts when I press on it." },
        { who: "system", t: "08:42:41", text: "Thank you. I'm notifying Dr. Smith's team immediately. Please keep your leg elevated and stay seated until they call you in the next 30 minutes." }
      ],
      extracted: [
        { var: "calf_warmth", val: "true",   conf: 0.97 },
        { var: "calf_tenderness", val: "true", conf: 0.94 },
        { var: "calf_pain_scale", val: "6", conf: 0.91 },
        { var: "side", val: "left", conf: 0.99 },
        { var: "anticoag_taken_today_am", val: "false", conf: 0.96 }
      ],
      triggered_protocol: "DVT_Risk_Hip_v2",
      audio_dur: 47
    },
    {
      id: "p-mar",
      name: "Margaret Olsen",
      mrn: "MRN-48104",
      age: 72,
      sex: "F",
      procedure: "Right total knee replacement",
      surgeon: "Dr. M. Smith",
      pod: 2,
      protocol: "Knee Replacement Protocol v2.1",
      status: "warning",
      trend: "up",
      lastCheckin: "18 min ago",
      lastCheckinAt: "08:26",
      score: 0.58,
      triggers: ["Pain trending up (4→7)", "Sleep < 4h reported"],
      vitals: {
        hr: { value: 88, unit: "bpm", range: [60, 100], state: "stable" },
        spo2: { value: 97, unit: "%", range: [94, 100], state: "stable" },
        temp: { value: 99.1, unit: "°F", range: [97, 99.5], state: "stable" },
        pain: { value: 7, unit: "/10", range: [0, 3], state: "warning" },
        bp: { value: "128/78", unit: "mmHg", range: null, state: "stable" }
      }
    },
    {
      id: "p-jam",
      name: "James Whitaker",
      mrn: "MRN-48077",
      age: 58,
      sex: "M",
      procedure: "Laparoscopic cholecystectomy",
      surgeon: "Dr. R. Patel",
      pod: 1,
      protocol: "Lap Chole Protocol v1.4",
      status: "warning",
      trend: "flat",
      lastCheckin: "1 hr ago",
      lastCheckinAt: "07:44",
      score: 0.41,
      triggers: ["Nausea episodes (3 in 6h)"],
    },
    {
      id: "p-elv",
      name: "Elvia Cortez",
      mrn: "MRN-47999",
      age: 49,
      sex: "F",
      procedure: "Open reduction radius",
      surgeon: "Dr. K. Lee",
      pod: 6,
      protocol: "ORIF Upper Limb v1.0",
      status: "stable",
      trend: "down",
      lastCheckin: "31 min ago",
      lastCheckinAt: "08:13",
      score: 0.12,
      triggers: []
    },
    {
      id: "p-ben",
      name: "Bennett Park",
      mrn: "MRN-47812",
      age: 61,
      sex: "M",
      procedure: "L4-L5 microdiscectomy",
      surgeon: "Dr. R. Patel",
      pod: 3,
      protocol: "Spine Recovery v2.0",
      status: "stable",
      trend: "flat",
      lastCheckin: "12 min ago",
      lastCheckinAt: "08:32",
      score: 0.18,
      triggers: []
    },
    {
      id: "p-han",
      name: "Hana Mizuki",
      mrn: "MRN-47760",
      age: 54,
      sex: "F",
      procedure: "Right total knee replacement",
      surgeon: "Dr. M. Smith",
      pod: 5,
      protocol: "Knee Replacement Protocol v2.1",
      status: "stable",
      trend: "down",
      lastCheckin: "44 min ago",
      lastCheckinAt: "08:00",
      score: 0.09,
      triggers: []
    },
    {
      id: "p-arn",
      name: "Arnold Becher",
      mrn: "MRN-47611",
      age: 78,
      sex: "M",
      procedure: "Femoral bypass",
      surgeon: "Dr. K. Lee",
      pod: 2,
      protocol: "Vascular Recovery v1.2",
      status: "stable",
      trend: "flat",
      lastCheckin: "9 min ago",
      lastCheckinAt: "08:35",
      score: 0.22,
      triggers: ["Mild fatigue"]
    },
    {
      id: "p-the",
      name: "Theresa Quan",
      mrn: "MRN-47502",
      age: 69,
      sex: "F",
      procedure: "Left total hip replacement",
      surgeon: "Dr. M. Smith",
      pod: 7,
      protocol: "Hip Replacement Protocol v3.2",
      status: "stable",
      trend: "down",
      lastCheckin: "21 min ago",
      lastCheckinAt: "08:23",
      score: 0.07,
      triggers: []
    },
    {
      id: "p-ott",
      name: "Otto Brandt",
      mrn: "MRN-47411",
      age: 64,
      sex: "M",
      procedure: "Inguinal hernia repair",
      surgeon: "Dr. R. Patel",
      pod: 4,
      protocol: "General Surgery Recovery v1.1",
      status: "pending",
      trend: "flat",
      lastCheckin: "Missed 06:00",
      lastCheckinAt: "—",
      score: null,
      triggers: ["Missed check-in × 1"]
    }
  ],

  protocolList: [
    { id: "DVT_Risk_Hip_v2", name: "DVT Risk — Hip Replacement", version: "v2", live: true, owner: "Dr. M. Smith", patients: 14, fires7d: 3 },
    { id: "Pain_Escalation_v3", name: "Pain Escalation", version: "v3", live: true, owner: "Care Mgmt", patients: 47, fires7d: 9 },
    { id: "Fever_Postop_v1", name: "Post-op Fever Watch", version: "v1", live: true, owner: "Care Mgmt", patients: 47, fires7d: 2 },
    { id: "Sleep_Quality_v1", name: "Sleep Quality Monitor", version: "v1", live: true, owner: "Dr. R. Patel", patients: 23, fires7d: 5 },
    { id: "Wound_Discharge_v2", name: "Wound Discharge Triage", version: "v2", live: false, owner: "Dr. M. Smith", patients: 0, fires7d: 0 }
  ]
};
