defmodule Studysync.Repo.Migrations.BoardPageNodes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:board_nodes) do
      remove :color
      modify :label, :text, null: true
      add :page_number, :bigint, null: false
    end
  end

  def down do
    alter table(:board_nodes) do
      remove :page_number
      modify :label, :text, null: false
      add :color, :text, default: "default"
    end
  end
end
