defmodule Studysync.Repo.Migrations.AddUserTheme do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :theme, :text, null: false, default: "study_sync_default"
    end
  end

  def down do
    alter table(:users) do
      remove :theme
    end
  end
end
