defmodule Studysync.Repo.Migrations.AddBoardReactions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:board_reactions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :emoji, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :node_id,
          references(:board_nodes,
            column: :id,
            name: "board_reactions_node_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "board_reactions_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:board_reactions, [:node_id, :user_id, :emoji],
             name: "board_reactions_unique_reaction_index"
           )
  end

  def down do
    drop constraint(:board_reactions, "board_reactions_node_id_fkey")

    drop constraint(:board_reactions, "board_reactions_user_id_fkey")

    drop_if_exists unique_index(:board_reactions, [:node_id, :user_id, :emoji],
                     name: "board_reactions_unique_reaction_index"
                   )

    drop table(:board_reactions)
  end
end
