defmodule Studysync.Repo.Migrations.AddAnnotations do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:annotations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :type, :text, null: false
      add :color, :text, null: false, default: "peach"
      add :visibility, :text, null: false, default: "workspace"
      add :text, :text, null: false
      add :body, :text, null: false
      add :page_number, :bigint, null: false
      add :rect, :map, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :resource_id,
          references(:library_resources,
            column: :id,
            name: "annotations_resource_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "annotations_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end
  end

  def down do
    drop constraint(:annotations, "annotations_resource_id_fkey")

    drop constraint(:annotations, "annotations_user_id_fkey")

    drop table(:annotations)
  end
end
