defmodule Studysync.Repo.Migrations.SprintResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:sprints, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :start_page, :bigint, null: false
      add :end_page, :bigint, null: false
      add :duration_minutes, :bigint, null: false
      add :status, :text, null: false, default: "active"
      add :started_at, :utc_datetime_usec, null: false
      add :ended_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :resource_id,
          references(:library_resources,
            column: :id,
            name: "sprints_resource_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :workspace_id,
          references(:workspaces,
            column: :id,
            name: "sprints_workspace_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :started_by_id,
          references(:users,
            column: :id,
            name: "sprints_started_by_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end

    create table(:sprint_members, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :joined_at, :utc_datetime_usec, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :sprint_id,
          references(:sprints,
            column: :id,
            name: "sprint_members_sprint_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "sprint_members_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:sprint_members, [:sprint_id, :user_id],
             name: "sprint_members_one_per_user_per_sprint_index"
           )
  end

  def down do
    drop constraint(:sprint_members, "sprint_members_sprint_id_fkey")

    drop constraint(:sprint_members, "sprint_members_user_id_fkey")

    drop_if_exists unique_index(:sprint_members, [:sprint_id, :user_id],
                     name: "sprint_members_one_per_user_per_sprint_index"
                   )

    drop table(:sprint_members)

    drop constraint(:sprints, "sprints_resource_id_fkey")

    drop constraint(:sprints, "sprints_workspace_id_fkey")

    drop constraint(:sprints, "sprints_started_by_id_fkey")

    drop table(:sprints)
  end
end
