defmodule Studysync.Repo.Migrations.AddMilestoneMarkers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:milestone_markers, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :page_number, :bigint, null: false
      add :position, :map, null: false
      add :label, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :resource_id,
          references(:library_resources,
            column: :id,
            name: "milestone_markers_resource_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :created_by_id,
          references(:users,
            column: :id,
            name: "milestone_markers_created_by_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end
  end

  def down do
    drop constraint(:milestone_markers, "milestone_markers_resource_id_fkey")

    drop constraint(:milestone_markers, "milestone_markers_created_by_id_fkey")

    drop table(:milestone_markers)
  end
end
