defmodule Studysync.Repo.Migrations.BoardResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:board_nodes, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :label, :text, null: false
      add :position_x, :float, null: false
      add :position_y, :float, null: false
      add :color, :text, default: "default"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :resource_id,
          references(:library_resources,
            column: :id,
            name: "board_nodes_resource_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "board_nodes_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end

    create table(:board_edges, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :label, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :source_id,
          references(:board_nodes,
            column: :id,
            name: "board_edges_source_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :target_id,
          references(:board_nodes,
            column: :id,
            name: "board_edges_target_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :resource_id,
          references(:library_resources,
            column: :id,
            name: "board_edges_resource_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "board_edges_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end

    create unique_index(:board_edges, [:source_id, :target_id],
             name: "board_edges_unique_edge_index"
           )
  end

  def down do
    drop constraint(:board_edges, "board_edges_source_id_fkey")

    drop constraint(:board_edges, "board_edges_target_id_fkey")

    drop constraint(:board_edges, "board_edges_resource_id_fkey")

    drop constraint(:board_edges, "board_edges_user_id_fkey")

    drop_if_exists unique_index(:board_edges, [:source_id, :target_id],
                     name: "board_edges_unique_edge_index"
                   )

    drop table(:board_edges)

    drop constraint(:board_nodes, "board_nodes_resource_id_fkey")

    drop constraint(:board_nodes, "board_nodes_user_id_fkey")

    drop table(:board_nodes)
  end
end
