defmodule Studysync.Repo.Migrations.CollectiveInsight do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:collective_insights, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :page_number, :bigint, null: false
      add :synthesis, :text, null: false
      add :contributor_ids, {:array, :uuid}, null: false, default: []
      add :contributing_annotation_ids, {:array, :uuid}, null: false, default: []

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :resource_id,
          references(:library_resources,
            column: :id,
            name: "collective_insights_resource_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:collective_insights, [:resource_id, :page_number],
             name: "collective_insights_one_per_page_index"
           )
  end

  def down do
    drop constraint(:collective_insights, "collective_insights_resource_id_fkey")

    drop_if_exists unique_index(:collective_insights, [:resource_id, :page_number],
                     name: "collective_insights_one_per_page_index"
                   )

    drop table(:collective_insights)
  end
end
