defmodule Studysync.Repo.Migrations.BoardNodeTypes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:board_nodes) do
      modify :page_number, :bigint, null: true
      add :node_type, :text, null: false, default: "page"
      add :content, :map
    end
  end

  def down do
    alter table(:board_nodes) do
      remove :content
      remove :node_type
      modify :page_number, :bigint, null: false
    end
  end
end
