defmodule Studysync.Repo.Migrations.AddRubberStamps do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:rubber_stamps, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :note, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :milestone_id,
          references(:milestone_markers,
            column: :id,
            name: "rubber_stamps_milestone_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "rubber_stamps_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:rubber_stamps, [:milestone_id, :user_id],
             name: "rubber_stamps_one_per_user_per_milestone_index"
           )
  end

  def down do
    drop constraint(:rubber_stamps, "rubber_stamps_milestone_id_fkey")

    drop constraint(:rubber_stamps, "rubber_stamps_user_id_fkey")

    drop_if_exists unique_index(:rubber_stamps, [:milestone_id, :user_id],
                     name: "rubber_stamps_one_per_user_per_milestone_index"
                   )

    drop table(:rubber_stamps)
  end
end
